[package]
name = "troll-of-fame-rust"
version = "0.1.0"
authors = ["Oteku <thomas.haessle@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
proptest-derive = "0.1.0"
proptest = "^0.9"
